POSITIVE_WORDS = {
    "bagus",  
    "luar biasa",  
    "nyaman",  
    "ramah",  
    "bersih",  
    "puas",  
    "mantap",  
    "menyenangkan",  
    "memuaskan",  
    "terbaik",  
    "suka",  
    "senang",  
    "indah",  
    "menawan",  
    "istimewa",  
    "mengesankan",  
    "mewah",  
    "spektakuler",  
    "hebat",  
    "ceria",  
    "bahagia",  
    "keren",  
    "asri",  
    "sejuk",  
    "modern",  
    "terawat",  
    "rapih",  
    "fasilitas lengkap",  
    "strategis",  
    "privasi terjaga",  
    "suasana tenang",  
    "pelayanan prima",  
    "professional",  
    "cepat",  
    "efisien",  
    "makanan enak",  
    "sarapan lezat",  
    "harga terjangkau",  
    "terjangkau",  
    "worth it",  
    "memanjakan",  
    "rekomendasi",  
    "favorit",  
    "ramah anak",  
    "family friendly",  
    "romantis",  
    "dekat wisata",  
    "pemandangan indah",  
    "view bagus",  
    "view keren",  
    "sunrise indah",  
    "sunset menawan",  
    "pemandangan spektakuler"  
}

NEGATIVE_WORDS = {
    "buruk",  
    "kecewa",  
    "kotor",  
    "parah",  
    "tidak puas",  
    "jelek",  
    "mengecewakan",  
    "menyebalkan",  
    "bising",  
    "tidak nyaman",  
    "kurang baik",  
    "kacau",  
    "pelayanan lambat",  
    "tidak profesional",  
    "mahal",  
    "overprice",  
    "kemahalan",  
    "terlalu mahal",  
    "makanan tidak enak",  
    "bau",  
    "pengap",  
    "sumpek",  
    "panas",  
    "berisik",  
    "seram",  
    "angker",  
    "tidak aman",  
    "banyak nyamuk",  
    "kasur keras",  
    "kurang bersih",  
    "air kotor",  
    "air panas tidak berfungsi",  
    "wifi lemot",  
    "sinyal jelek",  
    "banyak kecoa",  
    "banyak semut",  
    "toilet bau",  
    "kamar sempit",  
    "kolam kotor",  
    "debu banyak",  
    "sprei bau",  
    "handuk kotor",  
    "ac rusak",  
    "ac bocor",  
    "wc mampet",  
    "listrik mati",  
    "pintu rusak",  
    "resepsionis cuek",  
    "staf tidak ramah",  
    "fasilitas jelek",  
    "tidak sesuai foto",  
    "zonk"  
}
